# Generated by Django 3.0.2 on 2021-01-12 20:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorial',
            name='data_publikacji',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
        ),
    ]
